### ISSUE TITLE
Crash when empty filename is passed

### ISSUE THREAD

**Issue by jengelh** [gap-system/gap#2662]
### Command list

```
clone && ./configure && make
./gap ""
```

### Observed behaviour

```
Error before error-handling is initialized: [ "List Element: <list>[1] must have an assigned value" 
 ]Error before error-handling is initialized: 
[...]
Syntax warning: Unbound global variable in /home/jengelh/obs/zu/science/gap/gap/lib/files.gd:615
    elif Length(arg) = 2  then
               ^
Segmentation fault (core dumped)
```

### Expected behaviour

Don't crash.

### Copy and paste GAP banner (to tell us about your setup)

```
> ./gap
 ┌───────┐   GAP 4.10dev-943-g528c88f of today
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-default64
 Configuration:  gmp 6.1.2, readline
 Loading the library and packages ...
#I  gapdoc package is not available. Check that the name is correct
#I  and it is present in one of the GAP root directories (see '??RootPaths')
#I  GAP: needed package gapdoc cannot be loaded
Error, failed to load needed package `gapdoc' (version >= 1.2) at /home/jengelh/obs/zu/science/gap/gap/lib/package.gi:1854 called from
func(  ); at /home/jengelh/obs/zu/science/gap/gap/lib/system.g:209 called from
<function "CallAndInstallPostRestore">( <arguments> )
 called from read-eval loop at /home/jengelh/obs/zu/science/gap/gap/lib/init.g:760
you can 'quit;' to quit to outer loop, or
you can 'return;' to continue
brk> 
```

### Extra info:

```
(gdb) r ""
[...]
Program received signal SIGSEGV, Segmentation fault.
0x0000000000580fad in CONST_PTR_BAG (bag=0x0) at src/gasman.h:303
303         return *(const Bag**)bag;
(gdb) bt
#0  0x0000000000580fad in CONST_PTR_BAG (bag=0x0) at src/gasman.h:303
#1  0x000000000058115d in CONST_ADDR_OBJ (obj=0x0) at src/objects.h:402
#2  0x0000000000581802 in ELM_PLIST (list=0x0, pos=1) at src/plist.h:206
#3  0x000000000058240d in TypeString (list=0x100000041bf8) at src/stringobj.c:543
#4  0x000000000050db72 in TYPE_OBJ_FEO (obj=0x100000041bf8) at src/opers.c:1714
#5  0x000000000050f196 in DoOperationNArgs (arg6=0x0, arg5=0x0, arg4=0x0, arg3=0x0, arg2=0x0, 
    arg1=0x100000041bf8, constructor=0, verbose=0, n=1, oper=0x10000001f830) at src/opers.c:2067
#6  DoOperation1Args (oper=0x10000001f830, arg1=0x100000041bf8) at src/opers.c:2193
#7  0x00000000004bcd17 in IntrFuncCallEnd (funccall=1, options=0, nr=1) at src/intrprtr.c:417
#8  0x0000000000564abb in EvalRef (ref=..., needExpr=1) at src/read.c:336
#9  0x0000000000565ca4 in ReadCallVarAss (follow=3221225728, mode=114 'r') at src/read.c:829
#10 0x0000000000567bab in ReadAtom (follow=3221225728, mode=114 'r') at src/read.c:1553
#11 0x0000000000567e18 in ReadFactor (follow=3221225728, mode=114 'r') at src/read.c:1626
#12 0x0000000000568015 in ReadTerm (follow=3221225728, mode=114 'r') at src/read.c:1676
#13 0x0000000000568169 in ReadAri (follow=3221225728, mode=114 'r') at src/read.c:1709
#14 0x00000000005682ca in ReadRel (follow=3221225728, mode=114 'r') at src/read.c:1748
#15 0x00000000005684b6 in ReadAnd (follow=3221225728, mode=114 'r') at src/read.c:1787
#16 0x0000000000568789 in ReadExpr (follow=3221225728, mode=114 'r') at src/read.c:1859
#17 0x0000000000565448 in ReadSelector (follow=3221225728, level=0) at src/read.c:607
#18 0x0000000000565c09 in ReadCallVarAss (follow=3221225728, mode=114 'r') at src/read.c:823
#19 0x0000000000567bab in ReadAtom (follow=3221225728, mode=114 'r') at src/read.c:1553
#20 0x0000000000567e18 in ReadFactor (follow=3221225728, mode=114 'r') at src/read.c:1626
#21 0x0000000000568015 in ReadTerm (follow=3221225728, mode=114 'r') at src/read.c:1676
#22 0x0000000000568169 in ReadAri (follow=3221225728, mode=114 'r') at src/read.c:1709
---Type <return> to continue, or q <return> to quit---
#23 0x00000000005682ca in ReadRel (follow=3221225728, mode=114 'r') at src/read.c:1748
#24 0x00000000005684b6 in ReadAnd (follow=3221225728, mode=114 'r') at src/read.c:1787
#25 0x0000000000568789 in ReadExpr (follow=3221225728, mode=114 'r') at src/read.c:1859
#26 0x0000000000565482 in ReadSelector (follow=3221225472, level=0) at src/read.c:612
#27 0x0000000000565c09 in ReadCallVarAss (follow=3221225472, mode=120 'x') at src/read.c:823
#28 0x0000000000567bab in ReadAtom (follow=3221225472, mode=120 'x') at src/read.c:1553
#29 0x0000000000567e18 in ReadFactor (follow=3221225472, mode=120 'x') at src/read.c:1626
#30 0x0000000000568015 in ReadTerm (follow=3221225472, mode=120 'x') at src/read.c:1676
#31 0x0000000000568169 in ReadAri (follow=3221225472, mode=120 'x') at src/read.c:1709
#32 0x00000000005682ca in ReadRel (follow=3221225472, mode=120 'x') at src/read.c:1748
#33 0x00000000005684b6 in ReadAnd (follow=3221225472, mode=120 'x') at src/read.c:1787
#34 0x0000000000568789 in ReadExpr (follow=3221225472, mode=120 'x') at src/read.c:1859
#35 0x000000000056ac16 in ReadEvalCommand (context=0x100000000050, evalResult=0x7fffffff7d78, 
    dualSemicolon=0x0) at src/read.c:2586
#36 0x000000000057dc8b in READ_GAP_ROOT (filename=0x7fffffff8db0 "lib/files.gd") at src/streams.c:472
#37 0x000000000057ec6f in FuncREAD_GAP_ROOT (self=0x10000000e570, filename=0x100000041100)
    at src/streams.c:1126
#38 0x00000000004a8cd8 in EvalOrExecCall (call=368, nr=1, ignoreResult=0) at src/funcs.c:166
#39 EvalFunccall1args (call=368) at src/funcs.c:321
#40 0x0000000000498486 in EvalUnknownBool (expr=368) at src/exprs.c:103
#41 0x0000000000498912 in EvalNot (expr=392) at src/exprs.c:228
#42 0x00000000005a5421 in ExecAssLVar (stat=408) at src/vars.c:167
#43 0x0000000000576b3d in EXEC_STAT (stat=408) at src/stats.c:48
#44 0x0000000000576ef7 in ExecSeqStatHelper (nr=7, stat=32) at src/stats.c:150
---Type <return> to continue, or q <return> to quit---
#45 ExecSeqStat7 (stat=32) at src/stats.c:194
#46 0x0000000000576b3d in EXEC_STAT (stat=32) at src/stats.c:48
#47 0x00000000004ac23d in ExecFuncHelper () at src/funcs.c:439
#48 0x00000000004ac401 in DoExecFunc (arg=0x7fffffff9ff0, narg=1, func=0x100000012c08) at src/funcs.c:507
#49 DoExecFunc1args (func=0x100000012c08, a1=0x1000000410f8) at src/funcs.c:529
#50 0x00000000004669b2 in DoWrap1args (self=0x100000012c08, arg1=0x1000000410f0) at src/calls.c:174
#51 0x00000000004bcd17 in IntrFuncCallEnd (funccall=0, options=0, nr=1) at src/intrprtr.c:417
#52 0x0000000000564abb in EvalRef (ref=..., needExpr=0) at src/read.c:336
#53 0x0000000000565ca4 in ReadCallVarAss (follow=3221225472, mode=120 'x') at src/read.c:829
#54 0x0000000000567bab in ReadAtom (follow=3221225472, mode=120 'x') at src/read.c:1553
#55 0x0000000000567e18 in ReadFactor (follow=3221225472, mode=120 'x') at src/read.c:1626
#56 0x0000000000568015 in ReadTerm (follow=3221225472, mode=120 'x') at src/read.c:1676
#57 0x0000000000568169 in ReadAri (follow=3221225472, mode=120 'x') at src/read.c:1709
#58 0x00000000005682ca in ReadRel (follow=3221225472, mode=120 'x') at src/read.c:1748
#59 0x00000000005684b6 in ReadAnd (follow=3221225472, mode=120 'x') at src/read.c:1787
#60 0x0000000000568789 in ReadExpr (follow=3221225472, mode=120 'x') at src/read.c:1859
#61 0x000000000056ac16 in ReadEvalCommand (context=0x100000000050, evalResult=0x7fffffffa4b8, 
    dualSemicolon=0x0) at src/read.c:2586
#62 0x000000000057dc8b in READ_GAP_ROOT (filename=0x7fffffffb4f0 "lib/read1.g") at src/streams.c:472
#63 0x000000000057ec6f in FuncREAD_GAP_ROOT (self=0x10000000e570, filename=0x100000013148)
    at src/streams.c:1126
#64 0x00000000004a8cd8 in EvalOrExecCall (call=120, nr=1, ignoreResult=0) at src/funcs.c:166
#65 EvalFunccall1args (call=120) at src/funcs.c:321
#66 0x0000000000498486 in EvalUnknownBool (expr=120) at src/exprs.c:103
---Type <return> to continue, or q <return> to quit---
#67 0x0000000000498912 in EvalNot (expr=144) at src/exprs.c:228
#68 0x0000000000576fb3 in ExecIf (stat=288) at src/stats.c:226
#69 0x0000000000576b3d in EXEC_STAT (stat=288) at src/stats.c:48
#70 0x0000000000576c81 in ExecSeqStatHelper (nr=2, stat=32) at src/stats.c:150
#71 ExecSeqStat2 (stat=32) at src/stats.c:169
#72 0x0000000000576b3d in EXEC_STAT (stat=32) at src/stats.c:48
#73 0x00000000004ac23d in ExecFuncHelper () at src/funcs.c:439
#74 0x00000000004ac401 in DoExecFunc (arg=0x7fffffffc720, narg=1, func=0x100000010798) at src/funcs.c:507
#75 DoExecFunc1args (func=0x100000010798, a1=0x100000013148) at src/funcs.c:529
#76 0x00000000004bcd17 in IntrFuncCallEnd (funccall=0, options=0, nr=1) at src/intrprtr.c:417
#77 0x0000000000564abb in EvalRef (ref=..., needExpr=0) at src/read.c:336
#78 0x0000000000565ca4 in ReadCallVarAss (follow=3221225472, mode=120 'x') at src/read.c:829
#79 0x0000000000567bab in ReadAtom (follow=3221225472, mode=120 'x') at src/read.c:1553
#80 0x0000000000567e18 in ReadFactor (follow=3221225472, mode=120 'x') at src/read.c:1626
#81 0x0000000000568015 in ReadTerm (follow=3221225472, mode=120 'x') at src/read.c:1676
#82 0x0000000000568169 in ReadAri (follow=3221225472, mode=120 'x') at src/read.c:1709
#83 0x00000000005682ca in ReadRel (follow=3221225472, mode=120 'x') at src/read.c:1748
#84 0x00000000005684b6 in ReadAnd (follow=3221225472, mode=120 'x') at src/read.c:1787
#85 0x0000000000568789 in ReadExpr (follow=3221225472, mode=120 'x') at src/read.c:1859
#86 0x000000000056ac16 in ReadEvalCommand (context=0x100000000050, evalResult=0x7fffffffcbb8, 
    dualSemicolon=0x0) at src/read.c:2586
#87 0x000000000057dc8b in READ_GAP_ROOT (filename=0x5e7f28 "lib/init.g") at src/streams.c:472
#88 0x00000000004b1075 in InitializeGap (pargc=0x7fffffffdc4c, argv=0x7fffffffdda8, 
    environ=0x7fffffffddc0) at src/gap.c:1853
---Type <return> to continue, or q <return> to quit---
#89 0x00000000004aea9b in realmain (argc=2, argv=0x7fffffffdda8, environ=0x7fffffffddc0) at src/gap.c:443
#90 0x00000000004aeba6 in main (argc=2, argv=0x7fffffffdda8, environ=0x7fffffffddc0) at src/gap.c:479
```

**Comment by ChrisJefferson** [comment]
Well spotted. (Hopefully) fixed in #2665 . We do just ignore the empty argument, which might seem strange, but it is was GAP has always done with command line arguments it does not understand.
